name: bms-dev
channels:
  - pytorch
  - rdkit
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - rdkit
  - opencv
  - pytorch 
  - torchvision
  - cpuonly
  - pytorch-lightning
  - jupyterlab
  - editdistance
  - imgaug
  - albumentations
  - transformers
  - pip:
    - click
    - tqdm
    - Pillow
    - deepsmiles
    - selfies
